### ISSUE TITLE
Enable Video Embeds

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#104]
Make so that it’s possible to embed a Vimeo video into the content area of pages. Just enable the standard behavior. The video could either go on a page with other stuff, or on a page of its own, and be linked to.

**Comment by halfempty** [comment]
@gehalber Is there anything about how the video is displayed on this page that you would change?

http://ihartley.staging.wpengine.com/video-test/
User: ihartley
Password: 4f2b7b35

**Comment by gehalber** [comment]
@halfempty 
Nope! Looks great!
