### ISSUE TITLE
Heckscher Scholars: Bullets

### ISSUE THREAD

**Issue by gehalber** [everythingtype/heckscher#106]
@halfempty 
We've been making some copy edits. Can you create a style for the bullets? The lines after the first line should indent so they line up with the beginning of the text on the first line. Make sense?

<img width="1417" alt="screen shot 2017-11-13 at 12 01 55 pm" src="https://user-images.githubusercontent.com/6076488/32738395-bd8bb2ba-c86a-11e7-91f7-0b6732f2143f.png">

**Comment by halfempty** [comment]
@gehalber Done
