### ISSUE TITLE
Highlighted Projects

### ISSUE THREAD

**Issue by gehalber** [everythingtype/heckscher#111]
Keep the title of this page as is (Highlighted Projects): https://www.heckscherfoundation.org/projects/

List all of the Signature Initiatives here, but don’t call them that. They will be called Highlighted Projects. 

Move all of the current Selected 2016 Projects to a new page called Selected 2016 Grantees. 

So there will be two distinct pages: Highlighted Projects and Selected 2016 Grantees. 

We will not use the title Signature Initiatives.

**Comment by halfempty** [comment]
@gehalber Okay, this is done:

https://www.heckscherfoundation.org/projects/

Please take a look and let me know if everything's how you intended

**Comment by gehalber** [comment]
@halfempty 
Looks good. Now that highlighted projects is on its own page, I don't think we need the show more/show less anymore.

**Comment by keningzhu** [comment]
I think we still need to rename the Selected 2016 Projects page to Selected 2016 Grantees 
The link on Highlighted Projects (to Selected 2016 Projects) is broken. 

Replace 'Signature Initiatives' with "highlighted projects" and remove link

**Comment by halfempty** [comment]
@gehalber Done!
@keningzhu Thanks for catching those. Done!

**Comment by gehalber** [comment]
Great!
