### ISSUE TITLE
create a page called Year in Review

### ISSUE THREAD

**Issue by keningzhu** [everythingtype/heckscher#123]
add it to the About Us section @halfempty 

post all the past “annual books” there in a grid of all the book covers that would be hyperlinked to the PDFs

**Comment by gehalber** [comment]
@halfempty 
Think we could make a quick and dirty page for all of the annual reports to look like this page: https://www.heckscherfoundation.org/projects/

I was thinking maybe these could link to a pdf for now.
But maybe it would link to an https://issuu.com/ page.

What do you think?

**Comment by halfempty** [comment]
@gehalber Would it be possible to pass the report PDFs to me via Dropbox? It's possible for me to build this page without having them (and add them later), but it would be simpler if I have them.

**Comment by gehalber** [comment]
Will do tonight.

**Comment by halfempty** [comment]
Closing this as it's been replaced by #131
