### ISSUE TITLE
Hide the entire section of selected 2016 grantees

### ISSUE THREAD

**Issue by gehalber** [everythingtype/heckscher#126]
@halfempty 
Is there a way to hide everything here for now?
Don't want to delete content, but hide it. Just curious. Let me know before proceeding.

**Comment by halfempty** [comment]
@gehalber Yes. We can remove it from the menu, then set the page itself to "draft."

**Comment by gehalber** [comment]
@halfempty let's hold on that for now

**Comment by halfempty** [comment]
Closing this as it's been replaced by #132
