### ISSUE TITLE
History text update

### ISSUE THREAD

**Issue by gehalber** [everythingtype/heckscher#127]
@halfempty 

I don't have access to edit the content on history. Going to paste it here. Can you update?

**Our History**
The history of the Heckscher Foundation for Children is a multifaceted story with three principal participants.

Charles August Heckscher, a visionary who achieved great financial success, believed that wealth should be shared with others less fortunate. He started the foundation as one of his many benefactions. Arthur Smadbeck, a friend of August Heckscher and fellow philanthropist, reluctantly took over a shattered financial and management structure and made possible the survival and emergence of the Heckscher Foundation as a major benefactor. Ruth Smadbeck, who ran the foundation for more than 50 years, brought to its philanthropic activities a lifelong dedication to, and love for, children.

**Foundation Building Opens, 1922**

The Heckscher Foundation was founded in 1921. Its assets consisted of land at Fifth Avenue between 104th and 105th Streets in New York City and securities intended to provide funds for the construction of a building on the site for the foundation’s operations. The original building opened in 1922, but its operating costs far exceeded its budget. As the Depression deepened, the foundation’s assets were in default, and the foundation itself was on the verge of collapse.

**Ruth & Arthur Smadbeck Revitalize the Foundation and 
Its Programs, 1930’s**

August Heckscher turned to Arthur and Ruth Smadbeck, financial equals who shared his deep dedication to public service. Arthur Smadbeck was one of the first and most prolific suburban real estate developers of the era. Until his death in 1977, he donated his time and efforts to building the profitable platform and endowment that allowed the foundation to support major outside charitable efforts, while also overseeing his own successful businesses and extensive philanthropic endeavors.
Ruth Smadbeck began as a volunteer several years after the foundation’s building opened and ran the foundation for over 50 years, including its multi-faceted programs in dance, orchestra, exercise, and swimming; the purchase and distribution of necessities for indigent children; a kindergarten; a theater; a craft room; a senior lounge; a photography group; a library; and a thrift shop, while at the same time broadcasting two radio programs each week offering advice 
and guidance on childcare.

**The Modern Day Foundation Evolves, 1980’s**

At Ruth Smadbeck’s death in 1986, annual distributions to charity had grown to over $1 million and assets exceeded $22 million. Louis Smadbeck, a renowned real estate entrepreneur and civic leader in his own right, became Chairman of the Heckscher Foundation in 1986 and continued in this capacity until his death in 1992. Virginia Sloane was elected President in 1986 and President Emeritus in 2012.

**A New Generation Assumes Leadership, 1990’s**

A new generation assumed leadership in 1997. Howard G. (Peter) Sloane became Chairman and CEO and continues to preside over the foundation’s many philanthropic projects. Today, the foundation’s assets have grown to well over $300 million and distributions to charity have dramatically increased.

**Comment by halfempty** [comment]
Done

**Comment by gehalber** [comment]
Thanks!
