### ISSUE TITLE
Our Approach Landing Page

### ISSUE THREAD

**Issue by gehalber** [everythingtype/heckscher#128]
@halfempty 
I want to clone [this page](https://www.heckscherfoundation.org/selected-grantees/) and do something like [this](https://www.dropbox.com/s/utqrsgtuljdce9w/Heckscher-Our-Approach-20180411-b.pdf?dl=0).

Notice how the formatting in Venture Philanthropy is a little different, but hoping that won't be too much of an issue. Let me know when you think you can get this done.

Thanks!

**Comment by halfempty** [comment]
Closing this as it's been replaced by #130
