### ISSUE TITLE
new Year in Review page

### ISSUE THREAD

**Issue by keningzhu** [everythingtype/heckscher#131]
- [x] New Year in Review page
- [x] this page should live in the Our Approach section instead of About Us.

@halfempty

**Comment by halfempty** [comment]
@keningzhu @gehalber This is ready for content...

https://www.heckscherfoundation.org/wp-admin/post.php?post=1547&action=edit

(I don't think I ever received the report PDFs? Also, do we need into text?)

**Comment by gehalber** [comment]
@halfempty 
Ok. Those pdfs are up in the media library. See file names that correspond to correct years. We also made thumbnail images for each book (also in media library). 

We will need some intro copy for the main page, but not for each book.

**Comment by halfempty** [comment]
@gehalber This page is launched
