### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#25]

**Comment by halfempty** [comment]
@gehalber The mobile nav-- is it fixed to the top of window? I had been thinking yes, but checking the comps makes me think maybe not? This looks like it's instead in-line with the content, rather than sitting on top?

![image](https://cloud.githubusercontent.com/assets/775543/8662259/938b765e-2983-11e5-8b0c-e4eaeb4c0fb5.png)

Let me know, thanks!

**Comment by gehalber** [comment]
Yes. Fixed to top of the window. The menu opens like the search does on the desktop (pushes the page down). 

Logo scrolls with the page though.

**Comment by halfempty** [comment]
@gehalber Ah... but being fixed and pushing down the page are mutually exclusive though, right? 

- Pushing content implies that it's sitting in the flow, at the top. When you open it, the height is increased, and the whole flow pushes down. But when you scroll, the menu scrolls too, going off screen.

- Fixed implies that it is outside the flow. The page scrolls, but the menu stays at the top, always within reach. When the menu is opened there's no effect on the rest of the content, 'cause it's on a layer below. Does this make sense?

I can imagine a hybrid, where there's an invisible box above the content that is set to mirror whatever height the nav is at... but it's not something I've ever seen in the wild, so I doubt that's what you mean. Or am I missing a crucial piece of understanding?

**Comment by gehalber** [comment]
Ah, totally! That makes sense. I think it's more important to fix the nav.

**Comment by halfempty** [comment]
@gehalber Okay, I *think* the homepage is all in, all sizes, excluding the mobile search form. Please take a look and let me know anything I missed / needs tweaking:

http://ihartley.staging.wpengine.com/

**Comment by halfempty** [comment]
@gehalber Okay, I *think* this page (or, more accurately, the modules it contains) are all in. Please take a look:

http://ihartley.staging.wpengine.com/grant-guidelines/

**Comment by halfempty** [comment]
@gehalber btw I notice I've broken one of the homepage elements, so I'll be back in there fixing that

**Comment by halfempty** [comment]
@gehalber okay, homepage bug fixed

**Comment by halfempty** [comment]
@gehalber I've touched much of the site now, including the Blue and and Green sections. Those entire sections should be ready to take a look at. 

On my to-do list are the following, mostly from the Red section:

- [ ] Our History
- [ ] Grid of News Stories
- [ ] Contact page
- [ ] also, the Search Form in the nav

**Comment by halfempty** [comment]
@gehalber @philipdibello Okay, I think I've "touched" everything. Please take a look. I'm especially on the look out for bugs -- things not lining up and similar.

I've been working in Chrome, so now I'll be switching over to FF and also IE for testing.

**Comment by halfempty** [comment]
@gehalber @philipdibello I've looked at it in IE, down to version 9, and am pleasantly surprised to say I saw no glitches! Ditto FF. So I'm feeling quite good about it, pending any comments y'all may have.
