### ISSUE TITLE
Featured Image Captions

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#43]
**@gehalber says:**

> Heckscher wants to make a quick tweak to the site. They want to show the captions in Featured Images. This image has a caption in the caption field. Can you style it and reveal them? Maybe it should be like the caption style for the Highlighted Project Call to action at the bottom of the pages? Nothing urgent, but if you could let me know when its done that would be great. Thanks!

**Comment by halfempty** [comment]
@gehalber Hmm, the background is already they grey color. Here's trying it on white. Feedback/direction welcome!

![image](https://cloud.githubusercontent.com/assets/775543/5746602/5019894e-9bf6-11e4-8654-b6f5d8e6b776.png)

http://ihartley.staging.wpengine.com/education-academic-support-projects/

**Comment by halfempty** [comment]
@gehalber Just a reminder about this one... let me know any feedback on these captions, and if I should apply them to live. Thanks!

**Comment by gehalber** [comment]
These look great. Thanks!

**Comment by halfempty** [comment]
Okay done
