### ISSUE TITLE
Audio Player Format

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#44]
![image](https://cloud.githubusercontent.com/assets/775543/6008579/6a4547e4-aae8-11e4-83fc-d06da7a6d7c4.png)

**Comment by gehalber** [comment]
Can you update this?

**Comment by halfempty** [comment]
@gehalber Ah! This totally dropped off my radar. Yes! I've done a quick fix to make it behave in the default way:

![image](https://cloud.githubusercontent.com/assets/775543/7341196/ae4eb57c-ec62-11e4-84dc-6a98c2714404.png)

And I'll return to make it match the design, which is:

![image](https://cloud.githubusercontent.com/assets/775543/7341199/cc2e91a2-ec62-11e4-8a7b-036823969e4a.png)

**Comment by gehalber** [comment]
Great. Thanks!

**Comment by halfempty** [comment]
@gehalber I took another look, and I think I have it to how we had it before it broke. It looks like this:

![image](https://cloud.githubusercontent.com/assets/775543/7357225/15a76e04-ecf3-11e4-8523-33f473804395.png)

As you can see, it's pretty much the default player with some Heckscher colors.

Do you want me to go further, and move to the big button from the mockups? I ask because it means we'll lose a bunch of the functionality the default player.

**Comment by gehalber** [comment]
Let’s hold off, but leave this thread open. Perhaps when we tackle the responsive (this summer!) we can evaluate.
