### ISSUE TITLE
Responsive iPad

### ISSUE THREAD

**Issue by philipdibello** [everythingtype/heckscher#45]
Hey Marty! Things are looking really great. We just have a few updates we were hoping you could get to. For iPad —

1. Change all h3’s on homepage to font-size: 23px

2. This also allows us to bring back descriptions for ‘Our Highlighted Projects” and “Venture Philanthropy”. We'll need to update the font-size to 13px for these to make them fit. 

![heckscher_qa_2](https://cloud.githubusercontent.com/assets/7120580/8937861/11927268-3529-11e5-9968-27717b9fb6b0.png)

**Comment by halfempty** [comment]
@philipdibello okay, this is in
