### ISSUE TITLE
Responsive Mobile

### ISSUE THREAD

**Issue by philipdibello** [everythingtype/heckscher#46]
Just a few things for mobile as well —

1. Currently the site flexes the main content well in between 767px and 400px, but instead the content should only begin flexing under 400px. 

— So to describe it a little differently, the main column should actually stay a max-width of 400px, the browser width increases or decreases the size of the margins only. 

— Below 400px the content should then begin flexing (as it behaves currently).  

<i>If you have any questions, let me know and I can run through this in more detail. I also tried to illustrate what we were intending in the image below.</i>

![heckscher_qa_4](https://cloud.githubusercontent.com/assets/7120580/8938366/3ec0185a-352c-11e5-9f8f-b65c1049eb92.png)

2. On image carousel arrows are no longer centered when the page width is reduced. 
(Love that you made it swipe-able!)

![screen shot 2015-07-28 at 1 31 05 pm](https://cloud.githubusercontent.com/assets/7120580/8938513/09288744-352d-11e5-9e70-11e308abdf88.png)

**Comment by halfempty** [comment]
@philipdibello Okay, I've put in a max-width on one of the homepage container elements. Is this more what you had in mind?
