### ISSUE TITLE
Chrome Icon Weirds

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#47]
An issue with the icon font, it seems

![image1](https://cloud.githubusercontent.com/assets/775543/9365135/86304dfe-4675-11e5-8af8-3c71a1032c1f.PNG)

**Comment by halfempty** [comment]
@gehalber I downloaded Chrome onto my phone and the icons are proper. Did some Googling and people say it can happen when the browser has an older version of the font files in the cache. So I've renamed the font files, which should prompt new versions to be downloaded. Take a look and let me know? Thanks!

**Comment by gehalber** [comment]
Great now. Looking good! Thanks!
