### ISSUE TITLE
Couple of Mobile Bugs

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#48]
On the phone I see a couple of layout bugs:

- [ ] The splash screen isn't quite tall enough. It's off by 15px or so.
- [x] The vertical centering within the homepage circles isn't doing. The text is instead aligned to the bottom.

**Comment by gehalber** [comment]
Yeah, let’s fix.

Thanks!

**Comment by halfempty** [comment]
@gehalber 

Vertical centering fixed. 

And I figured out what's going on with the splash screen -- sometimes there's a toolbar at the bottom of the window, but sometimes it's hidden. The page is caculating the height based on the toolbar being there, and there's not much we can do with regards to that.
