### ISSUE TITLE
Venture Philanthropy page

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#50]

**Comment by halfempty** [comment]
@gehalber question: Where on the site is this page going to love?

**Comment by halfempty** [comment]
@gehalber "Live"!

**Comment by gehalber** [comment]
It will replace the current Venture Philanthropy page.

**Comment by halfempty** [comment]
@gehalber Thanks!

**Comment by gehalber** [comment]
However, before we can go ahead and replace I need to coordinate with Heckscher about the content management and adding all of the signature initiatives.

**Comment by halfempty** [comment]
@gehalber Got it. I'm creating it here:

http://www.heckscherfoundation.org/about/venture-philanthropy-revised/
Password: etc

**Comment by halfempty** [comment]
@gehalber I've prepared a bit on the back-end.

The Venture Philanthropy (Revised) page has a number of fields that are specific to its layout. I've filled them in with the copy from the comps.

The pages for the Strategic Initiatives can now be created. Here's what's special about them:

- Create them as children of "Venture Philanthropy (Revised)";
- Using the Page Attributes box, set Template to "Signature Initiatives"
- Set the Title, Content and Featured Image as you normally would

That's it! And I'll begin on the front-end templates.

**Comment by halfempty** [comment]
@gehalber I've done the styling of the Signature Initiatives screens. Can you please take a look and provide notes:

http://www.heckscherfoundation.org/about/venture-philanthropy-revised/single-stop/

Thanks!

**Comment by gehalber** [comment]
Looking Awesome!! All good!

**Comment by halfempty** [comment]
@gehalber Did a bit more. The styling is just about there, please look and give feedback:

http://www.heckscherfoundation.org/about/venture-philanthropy-revised/

Note that the pop-over action on the Signature Initiatives isn't in yet, meaning they're clicking through to a new page. My next step will be to enable that overlay action we've discussed.

**Comment by gehalber** [comment]
This looks terrific. Can you just make these tweaks to line up with the graphic:

Catalytic Giving should be green
Strategic Partnerships should be orange

We will plan to update everything today and get final approval once you’re able to wire everything up.

Thanks! Great job on this.

Geoff

**Comment by halfempty** [comment]
@gehalber Ah yes, to match the graphic. Okay, that change is made.

**Comment by halfempty** [comment]
@gehalber I've added the lightbox functionality to the Venture page. I think it's done, from a development point of view. Take a look? Thanks!

**Comment by gehalber** [comment]
This is great. Would it be possible to add the functionality where licking anywhere on the background also closes out the view, as opposed to only the x button. What do you think?

**Comment by gehalber** [comment]
I’m going to have Heckscher start adding content to these pages. Once Venture Philanthropy is published, I’m guessing you need to make Venture Philanthropy the parent for the signature initiatives?

Thanks!

**Comment by gehalber** [comment]
@halfempty The Venture Philanthropy content has been updated.

We are going to use images in place of logos for the signature initiatives section, which means it will make more sense for us to print the names of each organization underneath the pictures in the grid. We'll supply designs.

Also, following up about the added functionality from above:
This is great. Would it be possible to add the functionality where licking anywhere on the background also closes out the view, as opposed to only the x button. What do you think?

**Comment by halfempty** [comment]
@gehalber Okay, this is also done 

http://www.heckscherfoundation.org/?page_id=1044

**Comment by gehalber** [comment]
Perfect. Thanks!
