### ISSUE TITLE
Venture Philanthropy graphic

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#51]
@gehalber Do you have an updated version of the Venture Philanthropy graphic, in the new fonts? If yes, either send to me or go ahead and upload it as the page's Featured Image. Thank you!

**Comment by gehalber** [comment]
Here you go! Thanks.

https://www.dropbox.com/s/8gbjyc98y1hc4pm/venture-philanthrophy.jpg?dl=0

**Comment by halfempty** [comment]
Thanks!
