### ISSUE TITLE
Signature Initiatives Subhead for each organization

### ISSUE THREAD

**Issue by gehalber** [everythingtype/heckscher#52]
We want to print the subhead for each organization in the grid. Here's a design...

![screen shot 2016-03-08 at 4 52 54 pm](https://cloud.githubusercontent.com/assets/6076488/13618091/386e3c3c-e550-11e5-9b98-9b1d054a8f48.png)

Same styling as these...
<img width="810" alt="screen shot 2016-03-08 at 4 49 18 pm" src="https://cloud.githubusercontent.com/assets/6076488/13618123/5a938d4e-e550-11e5-8a08-1064f627687a.png">

**Comment by halfempty** [comment]
@gehalber Okay, this is done, please take a look

http://www.heckscherfoundation.org/?page_id=1044
