### ISSUE TITLE
Signature Initiatives: Tablet Grid view

### ISSUE THREAD

**Issue by gehalber** [everythingtype/heckscher#54]
The grid’s content description is breaking out of their boxes. If there was a way to make sure it was always contained within the beige box rather than spilling over like it is now?

![screen shot 2016-04-11 at 6 00 32 pm](https://cloud.githubusercontent.com/assets/6076488/14608230/e042e418-0552-11e6-836e-fdd36e48fc8b.png)

**Comment by halfempty** [comment]
@gehalber Okay, fixed by increasing the height of the the box for a certain size range
