### ISSUE TITLE
Signature Initiatives: Strategic Partnerships button on Mobile

### ISSUE THREAD

**Issue by gehalber** [everythingtype/heckscher#55]
"Strategic Partnership” not centered

![img_4662](https://cloud.githubusercontent.com/assets/6076488/14608298/28fbbbb2-0553-11e6-900d-bbbd12d0997f.jpeg)

**Comment by halfempty** [comment]
@gehalber Fixed? Or I'm not seeing it...

![image](https://cloud.githubusercontent.com/assets/775543/15879558/c60b5b2e-2cea-11e6-85f7-168e3fdd69d6.png)
