### ISSUE TITLE
Signature Initiatives: Jumping to top on "close"

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#59]
After opening the lightbox, when you tap "close", you should be returned to the same scroll-point where you had been when you opened it. For some reason, you're getting punted up to the top of the page. (The same code, installed elsewhere, works. Something specific to this design is throwing it off.)

**Comment by gehalber** [comment]
Its working fine if I just click in the beige area, but when i hit close it brings me to the top.

**Comment by halfempty** [comment]
@gehalber Okay, I think I've fixed this one. The culprit turned out to be that we made the beige area clickable. After clicking the "Close" button, a click on the beige area would also be registered (because the Close button is nested within the beige area). It would try to close the lightbox again but since the lightbox was already closed at this point, some of the measurements it took would be off, resulting in scrolling back up the page.

I fixed it by creating a variable to track if the lightbox is indeed open, and to only try to close it if it is.
