### ISSUE TITLE
News: Wide boxes on News Landing

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#60]
**@gehalber said:**

We’re adding a new module to the news landing page for a message from the chairman. He’ll post one a quarter, so there will be 4 a year. They’re designated from regular news posts by taking up two columns, having a background color and getting a new titling treatment. 

We’re also adding the functionality to filter the listing by “Topics” which are the tags associated with posts. You can see the functionality on pages 5 (dropdown style) and 6 (list after filtered)

**Comment by halfempty** [comment]
We’re seeing the wide, two-column boxes always sharing a line by adding a single one-column box. What if there’s occasion where the wide box falls on a line that already has two singles? (Do you know what I mean?) CSS will, used naturally, leave a spot open and move the wide box to the next line. We can use Packery (nee Masonry) to fill in the empty spot, though posts won’t then be in strictly chronological order. (It’s also leaning on JavaScript to achieve layout, which we do sometimes though only when we must.) Is that ok?

Other thing I’m thinking about is the color coding. Should this be automatic, based on post-date? Or manual?

**Comment by halfempty** [comment]
**@gehalber said:**

I think we ought to use packery to adjust the boxes. In this case: function follows form. 

I like the idea of automatic color coding so Indya does have to worry about it.

**Comment by halfempty** [comment]
@gehalber Here's color-coding on the News Landing page:

http://ihartley.staging.wpengine.com/category/news/

What it doesn't have is the two-column width at Desktop sizes

**Comment by gehalber** [comment]
I think we can go live without it, and add in later.

Thanks!
