### ISSUE TITLE
News: Homepage Lightbox

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#61]
**@gehalber said:**

We’re adding that new module from the “News Landing” page onto the homepage as well. It’s the same styling and everything. 

Since that would leave a column open, we added a “newsletter sign up” module next to the “Chairmans Message” module. When you click this you would get a custom lightbox, seen on page 10.

**Comment by halfempty** [comment]
@gehalber Some progress on the homepage. I've the boxes in, and responsive:

![image](https://cloud.githubusercontent.com/assets/775543/18368855/c64ce864-75e7-11e6-867b-35c461f4a0bb.png)

The lightbox containing the sign-up form is next. Please take a look and let me know if it's how you intended:

http://ihartley.staging.wpengine.com/

Thanks!

**Comment by gehalber** [comment]
This looks great. Can you put the “Nurturing Nonprofit Boards” on the homepage instead? 

Thanks!

**Comment by gehalber** [comment]
And once you have all 5 articles in the system, can you push it live?

**Comment by halfempty** [comment]
@gehalber There's a couple of elements that need to be sewn-up before going live, so that users aren't led to dead-ends. I'll prioritize this sewing-up

**Comment by gehalber** [comment]
Great. thanks!

**Comment by halfempty** [comment]
@gehalber Homepage:

http://ihartley.staging.wpengine.com/#home

Re the enews subscribe form--
I've opened a MailChimp link in a new window. I've done this for time, and also for backwards compatibility. I can continue to work on it, layering in the lightbox window. Or I can leave it this way for now, if you prefer.

**Comment by gehalber** [comment]
This isn't opening for me at the moment. Goes here: http://eepurl.com/bul88H

**Comment by gehalber** [comment]
Ok. I think that's fine for now.

**Comment by halfempty** [comment]
Duplicate of #71
