### ISSUE TITLE
News: Chairmans Message Detail Page

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#62]
**@gehalber said:**

We’ve added some new features past what’s possible on these news detail pages currently.
- The Chairmans message gets a new header, similar to the block found on the landing page
- Theres now a pull quote style 
- At the bottom of the article we’re re-purposing the landing page module as a two column layout which links to the previous and next articles in the Chairman series.

**Comment by halfempty** [comment]
@gehalber Made some progress on the article page. Will you take a look and let me know any changes you'd like to see? Thanks!

http://ihartley.staging.wpengine.com/investing-in-leadership-and-mentorship/

**Comment by gehalber** [comment]
Nice Marty. This is looking really great. The only comment is if we can always hang quotation on the pull quote? 

Thanks!

g

**Comment by halfempty** [comment]
@gehalber Yes, but there's a part to think through... We can pull the first line to the left a bit, so that the quote is visually hung. However, if the quote character is missing, the line will still hang over.

Can we count on there always being a quote character?

**Comment by gehalber** [comment]
Yes. We’ll make that rule.
Thanks!
