### ISSUE TITLE
News: About Heckscher Landing

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#63]
**@gehalber said:**

- We’ve added at the bottom of the page, again using these chairmen’s message blocks. This time we’re using the one column style like they are at the bottom of “Chairmans Message Detail Page” (above, p.11).
- You’re able to sort this section by year
- We’ve added a newsletter sign up underneath this block.

**Comment by halfempty** [comment]
@gehalber Bit of progress on this:

http://ihartley.staging.wpengine.com/about/

I haven't done the drop-down for sorting by year. I'm thinking we can come back to add that?

And the email form is still to come. Should we write the copy for that?

**Comment by gehalber** [comment]
Looking really really good!
Yes, we can come back to the email sorting by year on the about page.
Heckscher has a writer that they like to use, so we’ll ask her to fill in this paragraphs for us.

Thanks Marty.

g
