### ISSUE TITLE
News: Color coding

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#64]
**@gehalber said:**

The module should be slotted within the grid chronologically, so depending on how much content Heckscher is posting will vary how many blocks are between each post.
The post’s are color coded like so:
Q1 Message — Grey
Q2 Message— Orange
Q3 Message — Green
Q4 Message — Blue

**Comment by halfempty** [comment]
Other thing I’m thinking about is the color coding. Should this be automatic, based on post-date? Or manual?

**Comment by halfempty** [comment]
**@gehalber said:**

I like the idea of automatic color coding so Indya does have to worry about it.

**Comment by gehalber** [comment]
That said, we’ve started printing these, and I think they should all correspond so now I’m voting for manual! 

Thanks!

**Comment by halfempty** [comment]
@gehalber Does the color coding extend to the pullquotes and links at the bottom? Or are those always red?

**Comment by gehalber** [comment]
Yes! Color coordinates to essay color. Thanks!
