### ISSUE TITLE
News: First article?

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#65]
@gehalber Do we have the first article(s) in the Strategic Philanthropy series? I ask 'cause when the code is ready, it will be good to have at least one Post in the system for the code to pull-in.

**Comment by gehalber** [comment]
I have five. I can drop those into the system here, or would you rather?

**Comment by halfempty** [comment]
@gehalber I can do them. Send them my way?

**Comment by gehalber** [comment]
Could I give you indesign files?
Otherwise I’ll have to put them into text editor and go through the italics.

**Comment by halfempty** [comment]
@gehalber Sure

**Comment by gehalber** [comment]
https://www.dropbox.com/sh/l3ji5njvpaw3l54/AAA1JoaHYt-ITeBwDPuyeyP2a?dl=0
https://www.dropbox.com/s/wwtyvd2i86oozea/219436_Article-5-etc-R3.indd?dl=0

**Comment by halfempty** [comment]
@gehalber What (past) dates should each of these be published on?

**Comment by halfempty** [comment]
@gehalber The article timing is, I think, all I need to launch

**Comment by gehalber** [comment]
Honestly, 3 of them were done all at the same time, but here are dates for you:

Scaling back on Scaling: SEPTEMBER 15, 2015

Funder Collaboration: February 23, 2016

Investing in Leadership: March 15, 2016

Funding Structures for Social Profit: May 24, 2016

Nurturing Nonprofit Boards: July 28, 2016

**Comment by halfempty** [comment]
@gehalber Got it, launched!
