### ISSUE TITLE
News: Bits of Copy

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#66]
@gehalber There are two bits of copy we could use:
1. The description of the Strategic Philanthropy series that introduces the links, on the About page
2. The sentences that make the case for subscribing to the enews, which appears on the About page and also in the Homepage lightbox.

**Comment by halfempty** [comment]
@gehalber And to clarify on this-- we can launch w/o these, and add later.

**Comment by halfempty** [comment]
@gehalber Geoff, we still have some provisional copy in a couple of places. Will Indya write us anything or are we cool with what we've been using?

**Comment by gehalber** [comment]
I'll need to get Zoe involved in this shortly.

**Comment by halfempty** [comment]
@gehalber Have you contacted Zoe on this one?

**Comment by gehalber** [comment]
From Zoe:

1. Strategic Philanthropy series:
We periodically publish articles and blog posts to share current inquiries and lessons learned from our funding.

2. Subscribe to receive our email newsletter and new Strategic Philanthropy articles as soon as they are published.
