### ISSUE TITLE
News: Gravity Forms + MailChimp for Enews Forms

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#67]
@gehalber The enews sign-up forms provided by Mailchimp pop open a new browser window to confirm the subscription. It would be smoother if they didn't. I think there's a way to do that, involving the Gravityforms WP plugin. It's something we can look at if desired.

**Comment by gehalber** [comment]
Cool. Let’s put this in the queue and take a look at it later.

**Comment by halfempty** [comment]
The existing, non-Gravity Form is on this page:
http://www.heckscherfoundation.org/about/

The desire is to use Gravity Forms both on that page and on the homepage, via Issue #71

**Comment by dabernathy89** [comment]
And a demo of the form in the home page modal in place of the Mailchimp form here:

http://ihartley.staging.wpengine.com/about/

**Comment by halfempty** [comment]
@dabernathy89 So far so good! It's very important to ETC that we try to match the mockups as closely as possible. In this case this means having only the email field, and arranging everything just so:

![image](https://cloud.githubusercontent.com/assets/775543/19744963/5ec2c5aa-9b95-11e6-949a-2b572b46004d.png)

Cool?

**Comment by dabernathy89** [comment]
Will have the styling cleaned up for these tomorrow.

BTW, no need to switch away from Gravity Forms at this point, but this plugin is also supposed to be very good: https://wordpress.org/plugins/mailchimp-for-wp/

**Comment by gehalber** [comment]
I think this one is done.

**Comment by gehalber** [comment]
Oops. Spoke too soon. Just noticed that the submit button appears to be on the second line in desktop. This is what I see in chrome:
![screen shot 2016-11-17 at 4 02 07 pm](https://cloud.githubusercontent.com/assets/6076488/20407457/7e4dfe34-acdf-11e6-806b-2af9a88ba798.png)

**Comment by dabernathy89** [comment]
@gehalber this is fixed now:

http://ihartley.staging.wpengine.com/about/
