### ISSUE TITLE
News: Double column listing

### ISSUE THREAD

**Issue by gehalber** [everythingtype/heckscher#68]
Marty, I think we should make this work next: where the Sloane essays take up two columns.

**Comment by halfempty** [comment]
@gehalber 10-4

**Comment by gehalber** [comment]
This will help our titles: subtitles.

**Comment by halfempty** [comment]
At desktop sizes, this:

![image](https://cloud.githubusercontent.com/assets/775543/19504022/06dc5540-957d-11e6-9068-d83036203409.png)

**Comment by dabernathy89** [comment]
Demo of the double wide items: http://ihartley.staging.wpengine.com/category/news/

**Comment by halfempty** [comment]
@dabernathy89 This looks good. I'm cool with closing this ticket.
