### ISSUE TITLE
Add SSL

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#69]
> Installing your free Let’s Encrypt SSL certificates for your installs and custom domains is simple with WP Engine. Go to the SSL section within your User Portal Installs and select “Add SSL Certificates” to get started. 

Applicable to both the "Main" and "Trustees" sites.

**Comment by dabernathy89** [comment]
I've ordered the SSL certs for both sites - when they do get installed, are we okay just forcing HTTPS across both sites completely?

**Comment by halfempty** [comment]
@dabernathy89 Yes

**Comment by dabernathy89** [comment]
BTW, chatted with WPE, and it sounds like the A record for the domain needs to be updated:

> So, from what I can see, the domain’s DNS needs to be update to point to: 104.196.144.125
> It is currenlty pointing to: 66.175.215.117

**Comment by halfempty** [comment]
@dabernathy89 @gehalber Okay, sure. We don't handle their DNS -- Heckscher has someone they work with for this -- so we'll reach out to them.

**Comment by halfempty** [comment]
@dabernathy89 @gehalber I spoke with Michael from ArchonOne, their tech support firm, about the DNS. I believe he now has the info he needs to make the change. We'll see.

**Comment by halfempty** [comment]
@dabernathy89 Got CC'd on a note from the guys working on the DNS. It says:

> I assume we are all set with this.  

So I think they've done their piece? Dan, can you check?

**Comment by dabernathy89** [comment]
Actually i'm still seeing `66.175.215.117` as the IP:

http://mxtoolbox.com/SuperTool.aspx?action=a%3awww.heckscherfoundation.org&run=toolpage#

**Comment by halfempty** [comment]
@dabernathy89 Thanks Dan. I've asked them to check again.

**Comment by halfempty** [comment]
@dabernathy89 They said they just made the change this afternoon, so are waiting for propagation. (I'm skeptical 'cause I thought they made the change previously, but hey.) Please check again tomorrow?

**Comment by dabernathy89** [comment]
IP address looks correct now - SSL is still borked, checking with WP Engine to see what's up.

**Comment by dabernathy89** [comment]
Ok they did some magic on their end and looks like we're good to go now.
