### ISSUE TITLE
News: Tags UI

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#70]
This:

![image](https://cloud.githubusercontent.com/assets/775543/19503840/f7dacb54-957b-11e6-9beb-7319fcde0cf8.png)

And:

![image](https://cloud.githubusercontent.com/assets/775543/19504054/2110be6a-957d-11e6-96a6-130489a8de71.png)

And:

![image](https://cloud.githubusercontent.com/assets/775543/19504129/90919322-957d-11e6-8a32-98b72f749d26.png)

**Comment by halfempty** [comment]
@gehalber In one mockup this says "Tags," while in another it says "Topics." Which is preferred?

**Comment by gehalber** [comment]
Topics

**Comment by dabernathy89** [comment]
@halfempty i'm looking for the section with 'Tags' so I can switch it to 'Topics', but I can't seem to find it.

**Comment by halfempty** [comment]
@dabernathy89 This actually refers to the creation of a NEW section / interface element. (The Tags vs Topics discussion is about how to label it.) So the task is to create this interface...

BUT! @gehalber, I notice that none of the Posts on the live site have actually been tagged. Will Indya and her staff begin to use tags once they know the functionality is in? Or are they just in-fact not very interested in tagging the posts?

**Comment by gehalber** [comment]
They have a tagging/content strategy that they will begin to employ once the nav system is ready.

**Comment by dabernathy89** [comment]
Will also have this UI worked up tomorrow.

**Comment by dabernathy89** [comment]
Call notes:

- dropdown text 'Topics' --> 'All Topics' (link as well)
- custom taxonomy

**Comment by dabernathy89** [comment]
Here is the topics dropdown: http://ihartley.staging.wpengine.com/category/news/

**Comment by halfempty** [comment]
@dabernathy89, looks good to me.

@gehalber, will you take a look and give any feedback?

http://ihartley.staging.wpengine.com/category/news/

Thanks!

**Comment by gehalber** [comment]
Cool! Thanks. 
I'm seeing two things:

1. I'm seeing a bright red dropdown for Topics. This should be gray in static state, and change to Heckscher red on hover.

2. The mobile dropdown is cutting off the right side. @philipdibello Can you take a look at this?

<img width="400" alt="screen shot 2016-11-10 at 11 06 07 pm" src="https://cloud.githubusercontent.com/assets/6076488/20204309/bed14634-a79c-11e6-9609-91be1124ab74.png">

**Comment by philipdibello** [comment]
@gehalber not sure what we can do here except leave it as-is or initiate the system default rolodex dropdown on iOS / android devices on tap.

**Comment by dabernathy89** [comment]
@philipdibello @gehalber That would also be kind of difficult since we are not using real HTML dropdown elements (they are difficult/impossible to style this way). I've adjusted the CSS to place the dropdowns on separate lines for mobile, which seems to help.

I've updated the colors on the dropdown too - the red was pulled from the mockup, but I think you wanted it to match the 'archive' dropdown, right?

**Comment by dabernathy89** [comment]
(I do see now that in the closed state in the mockup the dropdown was grey as well)

**Comment by gehalber** [comment]
@dabernathy89 Ok. Let's stack these, but can we make these adjustments:

- make the dropdowns fixed width
- distance between dropdowns 25px

See mockup...
![screen shot 2016-11-17 at 3 50 21 pm](https://cloud.githubusercontent.com/assets/6076488/20407329/debdd506-acde-11e6-8f86-2b22fb5d27c9.png)

**Comment by dabernathy89** [comment]
Ok, those have been updated.

http://ihartley.staging.wpengine.com/category/news/
