### ISSUE TITLE
Enews modal on Homepage

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#71]
This:

![image](https://cloud.githubusercontent.com/assets/775543/19504185/cc32a7cc-957d-11e6-8da8-0496ff61a9d0.png)

Examples of a modal elsewhere on the site can be found here:
http://www.heckscherfoundation.org/about/venture-philanthropy-revised/

I believe the code for that model is in `css/venture.css` and `js/venture.js`

**Comment by dabernathy89** [comment]
Here's a demo of the modal (not yet connected to Mailchimp):

http://ihartley.staging.wpengine.com/

**Comment by halfempty** [comment]
@dabernathy89 Modal functionality's looking good! As with the other form, it's important to match the mockup as closely as possible, design-wise. Please let us know if you encounter any difficulties.

**Comment by dabernathy89** [comment]
Makes sense, in this case (and in the form on the About page) I was copying the styles from the existing external Mailchimp page. I can adjust to match the image above

**Comment by dabernathy89** [comment]
Call notes

- discussed styling

**Comment by dabernathy89** [comment]
Modal is updated: http://ihartley.staging.wpengine.com/

**Comment by halfempty** [comment]
@dabernathy89 Let's please tighten up the visuals even more:

- max-width of 219px on the logo
- include the "Sign up for our Newsletter" heading, matching the fonts/colors from the InDesign
- max-width of 784px on the text and form, making sure the Submit button sites at the right edge of that.
- generally matching sizes / margins everywhere

Our objective is as near a pixel-perfect match to the InDesign as possible!

**Comment by gehalber** [comment]
@dabernathy89 this one looks like its good to go. The only change is the to make sure the subscribe box on the homepage hovers to white background and clickable anywhere within box like other boxes on homepage. Make sense?

<img width="974" alt="screen shot 2016-11-21 at 2 58 29 pm" src="https://cloud.githubusercontent.com/assets/6076488/20498413/218c6e32-affb-11e6-877e-1f20aed3ec6e.png">

**Comment by dabernathy89** [comment]
@gehalber ok, i've added that hover effect to the subscribe box.
