### ISSUE TITLE
News: Archive UI on About Us Page

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#72]
This:

![image](https://cloud.githubusercontent.com/assets/775543/19504318/085be866-957f-11e6-832f-21728e28bcd0.png)

This is similar (at least superficially) to the drop-down that already exists on this page:
http://www.heckscherfoundation.org/category/news/

but is for the Venture Philanthropy section of the About Us page, here:
http://www.heckscherfoundation.org/about/

The intention is to show the 4 most recent, then have a UI to switch between years.

**Comment by dabernathy89** [comment]
This look about right?

http://ihartley.staging.wpengine.com/about/

That just uses the same implementation as the news dropdown. If you want them to display on that same page, something like this, we could do that too:

http://ihartley.staging.wpengine.com/about/?year=2015

**Comment by dabernathy89** [comment]
Following up on this one @halfempty

**Comment by dabernathy89** [comment]
Call notes:

- change to AJAX
- Change 'archive' to 'recent'
- change dropdown text to current selected 'link'
- underline current selected 'link' in list of links

**Comment by dabernathy89** [comment]
Hey, here's the updated demo of this: http://ihartley.staging.wpengine.com/about/

**Comment by halfempty** [comment]
@dabernathy89 Looks great!
