### ISSUE TITLE
Table styling

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#73]
@philipdibello meet @dabernathy89, @dabernathy89 meet @philipdibello.

Phil is working on designs for a couple of tables that are going to be added to the content of this site. 

Phil-- will you post here when they're ready? And Dan, will you take a look when those come in? Thanks, both!

**Comment by dabernathy89** [comment]
Hey Philip!

Definitely will - just a quick reminder that I'm heading out of town tomorrow though.

**Comment by dabernathy89** [comment]
Call notes

- received PDF and InDesign files

**Comment by gehalber** [comment]
@dabernathy89 @halfempty Hi guys, would it be possible that once you've styled the tables could you also flow the copy into the respective pages? That would be super helpful in regards to workflow since you're already in there.  Below is the link to .docs in any case. Let me know and appreciate it.
https://www.dropbox.com/sh/52uj1bmsd3mabs8/AADULD-Z7z-K70KwUhMOuJtLa?dl=0

**Comment by dabernathy89** [comment]
Still working on this one. I can definitely get that content in there, too.

**Comment by gehalber** [comment]
Thanks! If you have multiple things going on, just wanted to mention this one is a priority.

**Comment by dabernathy89** [comment]
Here are those two pages, let me know if it looks like I set this up right:

http://ihartley.staging.wpengine.com/grant-guidelines/
http://ihartley.staging.wpengine.com/education-academic-support/

**Comment by gehalber** [comment]
Thanks for turning this on a dime.

Two things:

1. The bounding border around entire table should be 2px
2. The Subheads at top should be regular weight and centered vertically. Header cell should be 95px tall.

Also, @dabernathy89 for whatever reason if you don't @ my name I won't get an email notification and won't know if you if you need my attention. Thanks!

**Comment by dabernathy89** [comment]
@gehalber Thanks - I cleaned up the borders (there were a couple color issues I noticed too and took down the font weight on the headers.

Are you sure about the height on the headers? In the mockup I've got they are 51px tall. I've got it at 52px so I can keep an even amount of padding above and below.

**Comment by gehalber** [comment]
Looking good. One tweak from client, then we're done. Thanks!

Hi Geoff,
There is one change. For the education and academic support table, there should be a line under the first sentence in each table to show that it is a division equation.

# students in program who enrolled in college within 6 months of graduating from high school
Total number of students who graduated from high school

**Comment by dabernathy89** [comment]
@gehalber apologies for the delay - I have added some dividing lines in the table: http://ihartley.staging.wpengine.com/education-academic-support/

**Comment by halfempty** [comment]
@gehalber @philipdibello Geoff or Philip, can you comment on how you'd like the lines styled?

![image](https://cloud.githubusercontent.com/assets/775543/20364628/6dbba8a4-ac09-11e6-8c13-daf7b434d354.png)

**Comment by gehalber** [comment]
This is fine as is, but I just realized that the horizontal lines that divide each section and go across two columns should be blue. Once that is done, we can close. Thanks.

**Comment by gehalber** [comment]
Also, please center the text in the equation fields. thanks

**Comment by gehalber** [comment]
Hi @dabernathy89 just wanted to follow up about this. Let me know if you can get to this today or tomorrow. Thanks!

**Comment by dabernathy89** [comment]
Hey @gehalber - just updated those styles:

http://ihartley.staging.wpengine.com/education-academic-support/

**Comment by gehalber** [comment]
Let’s just make sure those lines that cross both columns are also blue then this one is set. Thanks.

**Comment by dabernathy89** [comment]
I had them blue initially, but noticed that they are grey in the mockup. Do you want to switch that?

**Comment by gehalber** [comment]
Yes. Thanks!

**Comment by dabernathy89** [comment]
That is updated now: http://ihartley.staging.wpengine.com/education-academic-support/
