### ISSUE TITLE
Staging URLs for all new items

### ISSUE THREAD

**Issue by gehalber** [everythingtype/heckscher#74]
@dabernathy89 can you paste in all the URLs to the new pages you've been developing here? I'm planning to share with Heckscher asap as soon as finish this off and just want to have them all in one place. thanks!

**Comment by dabernathy89** [comment]
Hey @gehalber - I don't believe we've added any *new* pages through the updates I've been making (@halfempty - let me know if I may have forgotten any).

Here are the pages that have been through updates:

- http://ihartley.staging.wpengine.com/
  - updated 'Subscribe to our Newsletter' box to incorporate modal
- http://ihartley.staging.wpengine.com/about/
  - added new navigation to 'Strategic Philanthropy Series' section
  - updated Newsletter subscribe section styling and replaced Mailchimp form with Gravity Form
- http://ihartley.staging.wpengine.com/category/news/
  - added new Topics taxonomy with navigation dropdown
  - allowed Strategic Philanthropy news items to span 2 columns
- http://ihartley.staging.wpengine.com/education-academic-support/
  - new table styling
- http://ihartley.staging.wpengine.com/grant-guidelines/
  - new table styling

**Comment by gehalber** [comment]
Thanks!!

**Comment by halfempty** [comment]
@gehalber Are we holding a bunch of updates on Staging for approval by the client? Or may this stuff go live?

**Comment by gehalber** [comment]
Yes, we’re holding on these until Heckscher approves.

**Comment by gehalber** [comment]
@halfempty @dabernathy89 

Can you please publish all of the above? And let me know when its up. Thanks!!

**Comment by dabernathy89** [comment]
@gehalber @halfempty 

I have just pushed up the theme and content changes. I opened a new issue re: Mailchimp / newsletter configuration.
