### ISSUE TITLE
HTTPS / CSS issue

### ISSUE THREAD

**Issue by dabernathy89** [everythingtype/heckscher#75]
I just noticed this error in the console on the live site, which must be new from when we set up SSL:

> Mixed Content: The page at 'https://www.heckscherfoundation.org/' was loaded over HTTPS, but requested an insecure stylesheet 'http://ihartley.staging.wpengine.com//wp-content/themes/heckscher/fonts/203464/7476BAE4237D73278.css'. This request has been blocked; the content must be served over HTTPS.

Looks like that CSS is being loaded from "cloud.typography.com/7239512/740324/css/fonts.css".

**Comment by halfempty** [comment]
@gehalber Can you email me the cloud.typography credentials? I'd like to check the settings

**Comment by gehalber** [comment]
U: cfigueroa@heckscherfoundation.org
P: EverythingType

**Comment by halfempty** [comment]
Done
