### ISSUE TITLE
Website type styles

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#76]
**@gehalber says:**

I noticed on this page that the type styles are incorrect. Not sure why but just wanted to alert you to this. There might be a formatting issue in the WYSIWYG?

https://www.heckscherfoundation.org/board-staff/

**Comment by halfempty** [comment]
@gehalber I'm seeing these as Mercury. Is that not correct? What type treatment are you expecting to take effect here?

**Comment by gehalber** [comment]
Not sure what happened, but they're fine now. We'll close it out. It was Arial bold.
