### ISSUE TITLE
Signature Initiatives?

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#80]
@gehalber Wrapping my head around this content... the various pages under 2016 Projects appear to be updated versions of the pages we currently have in the Highlighted Projects section, yeah?

But with regards to the Signature Initiatives... these appear to be the same pages that are currently available under the Venture Philanthropy page. Are they the same, or merely similar? If they are the same, are we moving them out of Venture Philanthropy and into this section?

**Comment by gehalber** [comment]
@halfempty Right! Highlighted Projects is now becoming the home for Signature Initiatives and  2016 Projects—updated content currently in Highlighted projects.

Signature Initiatives is moving from Venture Philanthropy over to Highlighted Projects. Venture Philanthropy will no longer house the Signature Initiatives.
