### ISSUE TITLE
About Us > Recent Grants

### ISSUE THREAD

**Issue by gehalber** [everythingtype/heckscher#81]
@halfempty 
We decided to remove "Recent Grants" from this section because that all exists under now "Highlighted Projects".

**Let's perform this list of redirects...**
All of these:
https://www.heckscherfoundation.org/recent-grants/
https://www.heckscherfoundation.org/education-academic-support-recent-grants/
https://www.heckscherfoundation.org/arts-education-recent-grants/
https://www.heckscherfoundation.org/health-recreation-social-services-recent-grants/
https://www.heckscherfoundation.org/workforce-development-recent-grants/
https://www.heckscherfoundation.org/capacity-building-recent-grants/

will redirect to:
https://www.heckscherfoundation.org/projects/

**Comment by halfempty** [comment]
Done
