### ISSUE TITLE
Strategic Philanthropy Series

### ISSUE THREAD

**Issue by gehalber** [everythingtype/heckscher#85]
@halfempty 
Peter wants to move his essays directly underneath the "Chairman's Message" on this page:
https://www.heckscherfoundation.org/about/

Keep the color backgrounds the same as they are: Strategic Philanthropy Series on white; About us navigation on cream

**Comment by gehalber** [comment]
@halfempty 
Scratch that.

Strategic Philanthropy Series is going to get its own page on the site.
After "Our History" in the "About us" section.

In addition, the button on the homepage will lead to the landing page for the series, not to a specific article.

**Comment by halfempty** [comment]
@gehalber Okay, I've got Strategic Philanthropy moved to its own page. Take a look?

http://ihartley.staging.wpengine.com/about/strategic-philanthropy/

**Comment by gehalber** [comment]
@halfempty
Looks good. I need those guys to write a little description about this page cause it's not super clear what it is. 

type in mobile looks a little funky. Also archiv dropdown once clicked won't close if I click somewhere else on page or the dropdown again.

**Comment by halfempty** [comment]
@gehalber Hmm... ok, I've tweaked the CSS slightly to improve a couple of things at small sizes. But if there's more funkiness that's bothering you, please send screenshots.

Dropdown behavior-- I'm not sure I'm encountering the problem. Can you reproduce it? And then tell me more, if possible?
