### ISSUE TITLE
Strategic Philanthropy Series on homepage

### ISSUE THREAD

**Issue by gehalber** [everythingtype/heckscher#88]
@halfempty 
Rather than pointing to individual essays by Peter, the call to action button should point to the landing page for Strategic Philanthropy Series. Let's just replace the type to be "Strategic Philanthropy Series" and keep his name/title as is. 

![screen shot 2017-03-18 at 1 16 40 am](https://cloud.githubusercontent.com/assets/6076488/24069199/8fb44e60-0b78-11e7-86a1-feb0bd7e56a5.png)

**Comment by halfempty** [comment]
@gehalber Okay,  Strategic Philanthropy updated on the homepage. Take a look?

http://ihartley.staging.wpengine.com/
