### ISSUE TITLE
Last tweaks

### ISSUE THREAD

**Issue by gehalber** [everythingtype/heckscher#89]
@halfempty

Last tweaks from Peter:

- [x] It should say “selected 2016 projects” in the menu as it does in the text

- [x] You have Scaling back on Scaling twice –  In any event I don’t see the benefit of having them separated by years 2015 and 2016 – why not just have them all together? Let's remove the dropdown.
 
- [ ] The box that is empty and now says “Strategic Philanthropy” Should say “Strategic Philanthropy Series”
 
- [ ] How about this in the box: “The Strategic Philanthropy Series provides short analyses of key policy and other topics relevant to the Heckscher Foundation mission. “

**Comment by halfempty** [comment]
@gehalber The boxes he's referring to... "The box that is empty and now says “Strategic Philanthropy” Should say “Strategic Philanthropy Series”" and “The Strategic Philanthropy Series provides short analyses of key policy and other topics relevant to the Heckscher Foundation mission. “

Where's this?

**Comment by gehalber** [comment]
These nav boxes lower on the landing page.

<img width="840" alt="screen shot 2017-03-21 at 9 41 06 am" src="https://cloud.githubusercontent.com/assets/6076488/24149935/9cd45866-0e1a-11e7-91e2-f5264c960f2a.png">

As well as the introduction on this page, underneath "by Peter Sloane"
![screen shot 2017-03-21 at 9 42 40 am](https://cloud.githubusercontent.com/assets/6076488/24149978/c5e4f6e8-0e1a-11e7-9fc2-d78bc661f32a.png)

**Comment by halfempty** [comment]
@gehalber okay these are in

**Comment by gehalber** [comment]
Sweet. Thanks
