### ISSUE TITLE
Scholars: Fakt Slab font

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#90]
@gehalber Looks like this design introduces a new font -- Fakt Slab. Should I go ahead and buy it?
 Or would you like to take care of it (keeping the license etc in your name)?

**Comment by gehalber** [comment]
Yeah, I'll go ahead and purchase today.

**Comment by halfempty** [comment]
@gehalber I'm going to buy this, unless you tell me you've already done it...

**Comment by gehalber** [comment]
Go for it.
