### ISSUE TITLE
Splash animation on mobile?

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#91]
@gehalber Looking at the latest mockups... how do you want the interaction on the splash to happen on mobile? (I see the animation showing desktop)

Do you want the splash to slide-up and have the "About Us" are already in-place under it? Or do you want the About Us to slide up? Or... some other thing? Cheers

**Comment by gehalber** [comment]
@halfempty I think it should act similarly to the desktop, where the about us slides up on top of the logo. Two layers.
