### ISSUE TITLE
Scholars: Breakpoints

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#94]
**@gehalber said:**

> Designed it for desktop at 1300px. Then shrank that design to be 900px wide in the way it would shrink in the browser. Then make new breakpoint design at 899px. New Margins, etc. And shrank that down to 600px. Then designed the mobile version for 375. And then scaled that version up to 599px. There are essentially 3 breakpoints. One at 600px; one at 900 px; and one at 1300. The 1300 version just scales to infinite.

**Comment by halfempty** [comment]
@gehalber Have I got this right?

Base screen-width - Use mockups labeled 375. The mockups labeled 599 show this scaled-up.

Breakpoint at 600px - Use mockups labeled 600. The mockups labeled 899 show this scaled-up.

Breakpoint at 900px - Use mockups labeled 900. 

Breakpoint at 1300px - Use mockups labeled 1300.

**Comment by gehalber** [comment]
@halfempty Yes!

**Comment by halfempty** [comment]
@gehalber I believe I've got all the breakpoints in. Please take a look and point out anything I've missed!

**Comment by gehalber** [comment]
Looking really good!
