### ISSUE TITLE
Screensaver

### ISSUE THREAD

**Issue by gehalber** [everythingtype/heckscher#95]
@halfempty 

Just listing things out. I know you're aware of some of this, but just posting anyway:

- [x] Screensaver doesn't disapper on scroll
- [x] Screensaver comes in too early. It should feel more like a surprise after you've left the window open for awhile. Maybe 30 second delay to initiate. Then every 10 seconds another shape gets added.
- [x] Screensaver doesn't disappear on touch devices

**Comment by halfempty** [comment]
@gehalber Last screensaver bug is fixed
