### ISSUE TITLE
Splash Screen and Navigation

### ISSUE THREAD

**Issue by gehalber** [everythingtype/heckscher#96]
@halfempty 
The nav and splash screen isn't quite what we had in mind. This is the animation that shows how we intended it. Basically the splash screen is layer in the background and the rest of the page scrolls over top of it.

https://www.dropbox.com/s/fweefx6kh0f79vu/00%20scholars%20header%2020161215%20A%20sm.mov?dl=0

**Comment by halfempty** [comment]
@gehalber Oh yes, of course... slipped my mind. Okay, did some work on this and it should be in now... please review.

**Comment by gehalber** [comment]
Cool. Looks good. 

The arrow doesn't look work in mobile.

**Comment by halfempty** [comment]
@gehalber Arrow done
