### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by gehalber** [everythingtype/heckscher#97]
@halfempty 
The navigation isn't working for me yet on desktop or mobile. I'm sure you know this, but FYI. Are you planning for the nav items to have unique URLs? Or # links?

**Comment by halfempty** [comment]
@gehalber Oh, right! I totally forgot the nav actually had to function, haha. Okay, did some work on it. Take a look?

**Comment by halfempty** [comment]
@gehalber Oh, spoke to soon... I just noticed I need to work on highlighting the current section.

**Comment by gehalber** [comment]
@halfempty 
Ok. sounds good.

**Comment by halfempty** [comment]
@gehalber Okay, the menu highlights are in. I wasn't exactly sure if you wanted them to match the color of the section... so I made them highlight to blue. Let me know if you intended something else!

**Comment by gehalber** [comment]
@halfempty 
Yes, could you have them match the color section and could them hover to their respective colors as well.

**Comment by halfempty** [comment]
@gehalber Done
