### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by halfempty** [everythingtype/heckscher#99]
@gehalber Here's an existential question... How overly contentious do we want to be about colors? That is, I noticed that the HEX colors I've been using aren't 100% the same as the HEX colors in a logo file I'm using on the "main" site. Should we specify "official" HEX values for the Heckscher brand, and then I can go through and make sure they're used everywhere? 

If you have time to do that, I'll use them. Otherwise don't worry, the differences are imperceptible.

**Comment by gehalber** [comment]
Good question. I think its probably ok if imperceptible. Thanks for taking a close look at that!
